baseURL = ""
languageCode = "en-us"
title = "Luke Segars"
theme = "luke"
googleAnalytics = ""

[params]
    author = "Luke Segars"
    description = "Product leader & learner, currently helping cities manage mobility at [@PassportHQ](https://passportinc.com)"
    githubUsername = "anyweez"
    accent = "olive"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "python", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/anyweez/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/anyweez/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/lukesegars"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/1527421/salis"
    name = "stack-overflow"
    weight = 5
